apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-tks-info
  namespace: argo
spec:
  entrypoint: updateTksApp
  arguments:
    parameters:
    - name: tks_info_host
      value: "127.0.0.1"
    - name: app_group_id
      value: "abbead61-ff2a-4af4-8f41-d2c44c745de7"
  volumes:
  - name: tks-proto-vol
    configMap:
      name: tks-proto
  templates:
  - name: updateTksApp
    inputs:
      parameters:
      - name: endpoints # Dict type
      - name: app_group_status
        value: "APP_GROUP_RUNNING"
    script:
      image: centos/python-38-centos7
      command: ["python"]
      env:
      - name: PYTHONPATH
        value: "/opt/protobuf/:/opt/rh/rh-python38/root/lib/python3.8/site-packages/:/opt/app-root/lib/python3.8/site-packages/"
      volumeMounts:
      - name: tks-proto-vol
        mountPath: "/opt/protobuf"
        readOnly: true
      source: |
        import subprocess
        import sys

        subprocess.check_call([sys.executable, "-m", "pip", "install",
        "grpcio", "protobuf"])

        import google.protobuf
        import grpc
        import info_pb2
        import info_pb2_grpc
        import common_pb2
        import common_pb2_grpc

        ip = "{{workflow.parameters.tks_info_host}}"
        port = 9111 # if not specified
        addr = "%s:%d" % (ip, port)
        print("tks-info addr: %s" % addr)

        with grpc.insecure_channel(addr) as channel:
            app_stub = info_pb2_grpc.AppInfoServiceStub(channel)

            res = app_stub.UpdateAppGroupStatus(info_pb2.UpdateAppGroupStatusRequest(app_group_id="{{workflow.parameters.app_group_id}}", status=common_pb2."{{workflow.parameters.app_group_status}}"))
            print("Response code from UpdateAppGroupStaus: %d" % res.code)

            # Can app_type be passed like this?
            for app_type, ep in {{inputs.parameters.endpoints}}:
              res = app_stub.UpdateApp(info_pb2.UpdateAppRequest(app_group_id="{{workflow.parameters.app_group_id}}", app_type="common_pb2."+app_type, endpoint=ep, metadata="{}"))
              print("Response code from UpdateApp: %d" % res.code)
