kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-additional-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-additional-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-additional-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - patch
  - create
  - delete
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - create
  - delete
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - watch
  - delete
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - delete
- apiGroups:
  - helm.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - get
  - delete
  - list
  - patch
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - create
  - get
  - delete
  - list
  - patch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - alertmanagers
  verbs:
  - create
  - get
  - delete
  - list
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - create
  - get
  - delete
  - list
  - watch
